# Generated by Django 2.1.7 on 2019-04-14 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190414_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Bad')], default=5)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('giver', models.CharField(blank=True, max_length=50)),
                ('reveiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Household')),
            ],
        ),
    ]
