# Generated by Django 2.1.7 on 2019-04-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='reveiver',
            new_name='receiver',
        ),
    ]
